name: Qodana Code Quality
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - new-trevor-view
      - new-toguro-view
      - new-football-view
      - new-bull-riders
jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.3
        with:
          args: --baseline,.qodana/qodana.sarif.json
          fail-threshold: 15
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
