name: Unity Tests Runner

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - new-trevor-view
      - new-toguro-view
      - new-football-view
      - new-bull-riders
      
jobs:
  test-runner:
    name: Tests Runner
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project-name:
          - mines-project
        platform:
          - WebGL
        project-path:
          - test-project
        test-mode:
          - playmode
          - editmode
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      
      # Cache Library
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ matrix.project-name }}-${{ matrix.platform }}-${{ hashFiles('**/Packages/manifest.json') }}
          restore-keys: |
              Library-${{ matrix.project-name }}-${{ matrix.platform }}-
              Library-${{ matrix.project-name }}-
              Library-
      
      # Test Runner
      - name: Unity Tests Runner
        uses: game-ci/unity-test-runner@v4
        id: MinesTests
        with:
          unityVersion: auto
          testMode: ${{ matrix.test-mode }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          gitPrivateToken: ${{ secrets.GH_TOKEN }}
          artifactsPath: ${{ matrix.test-mode }}-artifacts
          checkName: ${{ matrix.test-mode }} Test Results
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        
      # Upload Tests Results
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Test results for ${{ matrix.test-mode }}
          path: ${{ steps.MinesTests.outputs.artifactsPath }}
      
      # Upload Coverage Results -> Disabled
      - uses: actions/upload-artifact@v3
        if: ${{ false }}
        with:
          name: Coverage results for ${{ matrix.test-mode }}
          path: ${{ steps.MinesTests.outputs.coveragePath }}
